import { ArrowRight, Check, FlaskConical, ShieldCheck } from "lucide-react";
import type { RunDetail } from "@/lib/types";

export function CompletionCard({ run }: { run: RunDetail }) {
  const previewOnly = run.action?.mock === true && run.action?.mutated === false;
  const verified = run.verification?.verified === true;
  return <section className={`rounded-2xl border p-6 md:p-8 ${verified ? "border-[#b9ddc4] bg-[#eff8f1]" : "border-rose-200 bg-rose-50"}`}>
    <div className="flex items-start gap-4"><span className={`flex size-11 shrink-0 items-center justify-center rounded-xl ${verified ? "bg-[#d6efdc] text-[#277951]" : "bg-rose-100 text-rose-700"}`}>{verified ? <ShieldCheck className="size-6" /> : "!"}</span><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#548c67]">Runbook complete</p><h2 className="mt-1 text-xl font-semibold text-[#1d4930]">{verified ? previewOnly ? "Scenario preview verified" : "Operational issue resolved" : "Verification needs review"}</h2><p className="mt-1 text-sm text-[#607967]">{run.flight_id}{run.brief.where.origin && run.brief.where.destination ? ` · ${run.brief.where.origin} → ${run.brief.where.destination}` : ""}</p></div></div>
    <div className="mt-6 grid gap-3 rounded-xl border border-[#d8ebdb] bg-white/70 p-4 text-sm sm:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-wide text-[#819c86]">Problem</p><p className="mt-1 text-[#355840]">{run.brief.why.constraint?.reason || run.brief.so_what || "Investigation complete"}</p></div><div><p className="text-[10px] font-bold uppercase tracking-wide text-[#819c86]">{previewOnly ? "Proposed substitution" : "Action"}</p><p className="mt-1 flex items-center gap-2 font-mono font-semibold text-[#285b3c]">{run.brief.proposed_action.remove_crew_id || "—"} <ArrowRight className="size-4" /> {run.brief.proposed_action.replacement_crew_id || "—"}</p></div></div>
    <div className="mt-6 grid gap-3 text-xs text-[#345b42] sm:grid-cols-2 lg:grid-cols-3">{["Investigation complete", run.brief.validation.candidate_valid ? "Candidate validated" : "Candidate reviewed", run.brief.validation.simulation_safe ? "Simulation passed" : "Simulation reviewed", "Human approval received", previewOnly ? "Substitution previewed" : "Roster change applied", verified ? previewOnly ? "Original roster confirmed" : "Updated roster verified" : "Verification did not pass"].map((label) => <span key={label} className="flex items-center gap-2"><Check className="size-4 text-[#298052]" />{label}</span>)}</div>
    {previewOnly && <div className="mt-6 flex items-center gap-2 rounded-xl border border-[#c7e2ce] bg-white/80 px-4 py-3 text-xs font-medium text-[#3a7851]"><FlaskConical className="size-4" />This was a scenario preview. No crew assignment was changed.</div>}
  </section>;
}
